export const ALPHABET = "abcdefghijklmnopqrstuvwxyz".split("");

type Cat = {
  name: string;
  sign: string;
  characteristics: string;
  origin: string;
};

type CatData = {
  [key in (typeof ALPHABET)[number]]: {
    names: Cat[];
    background: string;
    description: string;
  };
};

export const CATSDATA: CatData = {
  a: {
    names: [
      {
        name: "Arlo",
        sign: "Un ami loyal",
        characteristics: "Courageux, protecteur",
        origin: "Anglo-Saxon",
      },
      {
        name: "Apollo",
        sign: "Dieu des arts",
        characteristics: "Créatif, brillant",
        origin: "Grec",
      },
      {
        name: "Ariel",
        sign: "Lion de Dieu",
        characteristics: "Fort, noble",
        origin: "Hébreu",
      },
      {
        name: "Ava",
        sign: "Source de vie",
        characteristics: "Énergique, joyeux",
        origin: "Latin",
      },
      {
        name: "Alfie",
        sign: "Sage conseiller",
        characteristics: "Intelligent, prudent",
        origin: "Anglais",
      },
      {
        name: "Amber",
        sign: "Pierre précieuse",
        characteristics: "Chaleureux, précieux",
        origin: "Anglais",
      },
      {
        name: "Ace",
        sign: "Le meilleur",
        characteristics: "Confiant, leader",
        origin: "Anglais",
      },
      {
        name: "Asher",
        sign: "Heureux et béni",
        characteristics: "Optimiste, chanceux",
        origin: "Hébreu",
      },
      {
        name: "Autumn",
        sign: "Saison de récolte",
        characteristics: "Paisible, réfléchi",
        origin: "Anglais",
      },
      {
        name: "Archie",
        sign: "Brave et audacieux",
        characteristics: "Courageux, aventureux",
        origin: "Anglais",
      },
      {
        name: "Anya",
        sign: "Grâce divine",
        characteristics: "Élégant, doux",
        origin: "Russe",
      },
      {
        name: "Atlas",
        sign: "Porteur du monde",
        characteristics: "Fort, résilient",
        origin: "Grec",
      },
      {
        name: "Axel",
        sign: "Père de la paix",
        characteristics: "Paisible, protecteur",
        origin: "Scandinave",
      },
      {
        name: "Aspen",
        sign: "Arbre robuste",
        characteristics: "Flexible, résistant",
        origin: "Anglais",
      },
      {
        name: "Aurora",
        sign: "Déesse de l'aube",
        characteristics: "Éclatant, lumineux",
        origin: "Latin",
      },
      {
        name: "Aiden",
        sign: "Petit feu vif",
        characteristics: "Passionné, énergique",
        origin: "Irlandais",
      },
      {
        name: "Amos",
        sign: "Porteur de fardeaux",
        characteristics: "Responsable, fort",
        origin: "Hébreu",
      },
      {
        name: "Archer",
        sign: "Maître archer",
        characteristics: "Précis, déterminé",
        origin: "Anglais",
      },
      {
        name: "Adele",
        sign: "Noble et aimable",
        characteristics: "Gracieux, élégant",
        origin: "Allemand",
      },
      {
        name: "Ainsley",
        sign: "Prairie paisible",
        characteristics: "Naturel, serein",
        origin: "Anglais",
      },
    ],
    background: "/cat1.png",
    description: `Les noms de chat commençant par 'A' sont souvent associés à l'audace et à l'aventure. Parfait pour les chats qui montrent une personnalité courageuse et indépendante. "Aslan", par exemple, inspiré par le lion majestueux de Narnia, convient bien à un chat fier et protecteur.`,
  },
  b: {
    names: [
      {
        name: "Bella",
        sign: "Symbole de beauté",
        characteristics: "Gracieuse, élégante",
        origin: "Italien",
      },
      {
        name: "Bailey",
        sign: "Protecteur loyal",
        characteristics: "Loyal, fiable",
        origin: "Anglais",
      },
      {
        name: "Baxter",
        sign: "Le boulanger",
        characteristics: "Travailleur, créatif",
        origin: "Anglais",
      },
      {
        name: "Blaze",
        sign: "Flamme ardente",
        characteristics: "Passionné, intense",
        origin: "Anglais",
      },
      {
        name: "Benny",
        sign: "Petit béni",
        characteristics: "Chanceux, joyeux",
        origin: "Hébreu",
      },
      {
        name: "Bonnie",
        sign: "Bonne et belle",
        characteristics: "Agréable, charmante",
        origin: "Écossais",
      },
      {
        name: "Bruno",
        sign: "Brun et fort",
        characteristics: "Sérieux, robuste",
        origin: "Allemand",
      },
      {
        name: "Bobby",
        sign: "Gloire brillante",
        characteristics: "Brillant, sociable",
        origin: "Anglais",
      },
      {
        name: "Briar",
        sign: "Buisson protecteur",
        characteristics: "Protecteur, résilient",
        origin: "Anglais",
      },
      {
        name: "Brody",
        sign: "L'aventurier",
        characteristics: "Aventurier, audacieux",
        origin: "Écossais",
      },
      {
        name: "Bryn",
        sign: "Petite colline",
        characteristics: "Stable, serein",
        origin: "Gallois",
      },
      {
        name: "Bryce",
        sign: "Energie vivante",
        characteristics: "Énergique, unique",
        origin: "Gallois",
      },
      {
        name: "Beau",
        sign: "Beau garçon",
        characteristics: "Charmant, élégant",
        origin: "Français",
      },
      {
        name: "Basil",
        sign: "Roi noble",
        characteristics: "Noble, puissant",
        origin: "Grec",
      },
      {
        name: "Balthazar",
        sign: "Protecteur du roi",
        characteristics: "Sage, protecteur",
        origin: "Babylonien",
      },
      {
        name: "Bodhi",
        sign: "Éveil spirituel",
        characteristics: "Calme, spirituel",
        origin: "Sanskrit",
      },
      {
        name: "Blair",
        sign: "Plaine sereine",
        characteristics: "Paisible, naturel",
        origin: "Écossais",
      },
      {
        name: "Benedict",
        sign: "Béni et pieux",
        characteristics: "Bienveillant, pieux",
        origin: "Latin",
      },
      {
        name: "Barney",
        sign: "Ami réconfortant",
        characteristics: "Consolateur, amical",
        origin: "Hébreu",
      },
    ],
    background: "/cat2.png",
    description: `Les noms de chat commençant par 'B' évoquent souvent la bonté et la beauté. Idéal pour les chats gracieux et élégants. "Bella", par exemple, qui signifie "belle" en italien, est parfait pour une chatte élégante et charmante.`,
  },
  c: {
    names: [
      {
        name: "Cleo",
        sign: "Gloire de son père",
        characteristics: "Brillant, noble",
        origin: "Grec",
      },
      {
        name: "Casper",
        sign: "Trésorier royal",
        characteristics: "Sage, protecteur",
        origin: "Persan",
      },
      {
        name: "Cora",
        sign: "Fille douce",
        characteristics: "Pure, douce",
        origin: "Grec",
      },
      {
        name: "Cyrus",
        sign: "Leader fort",
        characteristics: "Leader, puissant",
        origin: "Persan",
      },
      {
        name: "Cedar",
        sign: "Arbre solide",
        characteristics: "Fort, résilient",
        origin: "Anglais",
      },
      {
        name: "Callie",
        sign: "Belle et aimante",
        characteristics: "Affectueuse, joyeuse",
        origin: "Grec",
      },
      {
        name: "Caleb",
        sign: "Cœur loyal",
        characteristics: "Loyal, courageux",
        origin: "Hébreu",
      },
      {
        name: "Chase",
        sign: "Chasseur agile",
        characteristics: "Rapide, déterminé",
        origin: "Anglais",
      },
      {
        name: "Coco",
        sign: "Nom sucré",
        characteristics: "Vif, joueur",
        origin: "Français",
      },
      {
        name: "Cassie",
        sign: "Pure et chaste",
        characteristics: "Douce, innocente",
        origin: "Grec",
      },
      {
        name: "Cosmo",
        sign: "Ordre universel",
        characteristics: "Calme, équilibré",
        origin: "Grec",
      },
      {
        name: "Clara",
        sign: "Claire et lumineuse",
        characteristics: "Éclairé, vif",
        origin: "Latin",
      },
      {
        name: "Carly",
        sign: "Petite et forte",
        characteristics: "Robuste, énergique",
        origin: "Anglais",
      },
      {
        name: "Cody",
        sign: "Aide utile",
        characteristics: "Serviable, loyal",
        origin: "Anglais",
      },
      {
        name: "Carmen",
        sign: "Chanson joyeuse",
        characteristics: "Joyeux, mélodieux",
        origin: "Latin",
      },
      {
        name: "Cora",
        sign: "Jeune fille",
        characteristics: "Pure, douce",
        origin: "Grec",
      },
      {
        name: "Clive",
        sign: "Vie près des collines",
        characteristics: "Serein, naturel",
        origin: "Anglais",
      },
    ],
    background: "/cat3.png",
    description: `Les noms de chat commençant par 'C' sont souvent associés à la créativité et à la curiosité. Parfait pour les chats intelligents et explorateurs. "Cleo", par exemple, signifie "gloire" en grec, ce qui convient bien à une chatte noble et digne.`,
  },
  d: {
    names: [
      {
        name: "Daisy",
        sign: "Fleur délicate",
        characteristics: "Douce, joyeuse",
        origin: "Anglais",
      },
      {
        name: "Duke",
        sign: "Noble leader",
        characteristics: "Royal, puissant",
        origin: "Anglais",
      },
      {
        name: "Dexter",
        sign: "Droiture et compétence",
        characteristics: "Intelligent, habile",
        origin: "Latin",
      },
      {
        name: "Daphne",
        sign: "Laurier",
        characteristics: "Gracieuse, forte",
        origin: "Grec",
      },
      {
        name: "Diego",
        sign: "Celui qui remplace",
        characteristics: "Loyal, courageux",
        origin: "Espagnol",
      },
      {
        name: "Darcy",
        sign: "Sombre et mystérieux",
        characteristics: "Mystérieux, élégant",
        origin: "Français",
      },
      {
        name: "Dahlia",
        sign: "Fleur majestueuse",
        characteristics: "Gracieuse, noble",
        origin: "Suédois",
      },
      {
        name: "Duncan",
        sign: "Guerrier brun",
        characteristics: "Courageux, fort",
        origin: "Écossais",
      },
      {
        name: "Dino",
        sign: "Petit et fort",
        characteristics: "Énergique, courageux",
        origin: "Italien",
      },
      {
        name: "Dora",
        sign: "Cadeau de Dieu",
        characteristics: "Généreuse, aimante",
        origin: "Grec",
      },
      {
        name: "Dylan",
        sign: "Fils de la mer",
        characteristics: "Paisible, aventureux",
        origin: "Gallois",
      },
      {
        name: "Dino",
        sign: "Petit et fort",
        characteristics: "Énergique, courageux",
        origin: "Italien",
      },
      {
        name: "Derek",
        sign: "Dirigeant du peuple",
        characteristics: "Leader, courageux",
        origin: "Allemand",
      },
      {
        name: "Delilah",
        sign: "Délicate",
        characteristics: "Gracieuse, douce",
        origin: "Hébreu",
      },
      {
        name: "Donovan",
        sign: "Chef sombre",
        characteristics: "Noble, puissant",
        origin: "Irlandais",
      },
      {
        name: "Dakota",
        sign: "Ami ou allié",
        characteristics: "Loyal, fiable",
        origin: "Amérindien",
      },
      {
        name: "Damon",
        sign: "Doux et docile",
        characteristics: "Affectueux, paisible",
        origin: "Grec",
      },
      {
        name: "Darla",
        sign: "Chérie bien-aimée",
        characteristics: "Aimante, douce",
        origin: "Anglais",
      },
      {
        name: "Dorian",
        sign: "Descendant de Dorus",
        characteristics: "Noble, fort",
        origin: "Grec",
      },
    ],
    background: "/cat4.png",
    description: `Les noms de chat commençant par 'D' évoquent souvent la dignité et la douceur. Idéal pour les chats gentils et affectueux. "Daisy", par exemple, qui signifie "fleur délicate", est parfait pour une chatte douce et joyeuse.`,
  },
  e: {
    names: [
      {
        name: "Ella",
        sign: "Lumière éclatante",
        characteristics: "Élégante, douce",
        origin: "Anglais",
      },
      {
        name: "Ethan",
        sign: "Fort et ferme",
        characteristics: "Déterminé, loyal",
        origin: "Hébreu",
      },
      {
        name: "Evelyn",
        sign: "Belle oiseau",
        characteristics: "Gracieuse, paisible",
        origin: "Anglais",
      },
      {
        name: "Elio",
        sign: "Soleil éclatant",
        characteristics: "Brillant, joyeux",
        origin: "Italien",
      },
      {
        name: "Esther",
        sign: "Étoile lumineuse",
        characteristics: "Inspirante, noble",
        origin: "Persan",
      },
      {
        name: "Ezra",
        sign: "Aide et soutien",
        characteristics: "Serviable, fort",
        origin: "Hébreu",
      },
      {
        name: "Elsa",
        sign: "Noble et joyeuse",
        characteristics: "Aimante, joyeuse",
        origin: "Allemand",
      },
      {
        name: "Elias",
        sign: "Le Seigneur est mon Dieu",
        characteristics: "Dévoué, pieux",
        origin: "Hébreu",
      },
      {
        name: "Ember",
        sign: "Braise ardente",
        characteristics: "Passionnée, vive",
        origin: "Anglais",
      },
      {
        name: "Evan",
        sign: "Jeune guerrier",
        characteristics: "Courageux, fort",
        origin: "Gallois",
      },
      {
        name: "Elise",
        sign: "Promesse de Dieu",
        characteristics: "Dévouée, aimante",
        origin: "Hébreu",
      },
      {
        name: "Emmett",
        sign: "Universel",
        characteristics: "Compréhensif, adaptable",
        origin: "Anglais",
      },
      {
        name: "Elara",
        sign: "Étoile brillante",
        characteristics: "Élégante, lumineuse",
        origin: "Grec",
      },
      {
        name: "Eddie",
        sign: "Gardien riche",
        characteristics: "Fiable, loyal",
        origin: "Anglais",
      },
      {
        name: "Elina",
        sign: "Rayon de lumière",
        characteristics: "Brillante, joyeuse",
        origin: "Scandinave",
      },
      {
        name: "Eldon",
        sign: "Colline sacrée",
        characteristics: "Sage, paisible",
        origin: "Anglais",
      },
      {
        name: "Erin",
        sign: "De l'Irlande",
        characteristics: "Fière, forte",
        origin: "Irlandais",
      },
      {
        name: "Eloise",
        sign: "Saine et entière",
        characteristics: "Énergique, joyeuse",
        origin: "Français",
      },
      {
        name: "Elliot",
        sign: "Dieu est élevé",
        characteristics: "Dévoué, fort",
        origin: "Hébreu",
      },
      {
        name: "Evelyn",
        sign: "Belle oiseau",
        characteristics: "Gracieuse, paisible",
        origin: "Anglais",
      },
    ],
    background: "/cat5.png",
    description: `Les noms de chat commençant par 'E' sont souvent associés à l'énergie et à l'élégance. Parfait pour les chats dynamiques et gracieux. "Ella", par exemple, signifie "lumière éclatante" et convient bien à une chatte lumineuse et élégante.`,
  },
  f: {
    names: [
      {
        name: "Felix",
        sign: "Heureux et chanceux",
        characteristics: "Joyeux, optimiste",
        origin: "Latin",
      },
      {
        name: "Fiona",
        sign: "Blanche et juste",
        characteristics: "Pure, gracieuse",
        origin: "Gaélique",
      },
      {
        name: "Finn",
        sign: "Blanc et juste",
        characteristics: "Honnête, courageux",
        origin: "Irlandais",
      },
      {
        name: "Freya",
        sign: "Déesse de l'amour",
        characteristics: "Aimante, belle",
        origin: "Scandinave",
      },
      {
        name: "Fletcher",
        sign: "Fabricant de flèches",
        characteristics: "Créatif, précis",
        origin: "Anglais",
      },
      {
        name: "Faye",
        sign: "Fée enchantée",
        characteristics: "Mystérieuse, douce",
        origin: "Anglais",
      },
      {
        name: "Flynn",
        sign: "Fils du roux",
        characteristics: "Énergique, audacieux",
        origin: "Irlandais",
      },
      {
        name: "Florence",
        sign: "Fleurissante",
        characteristics: "Gracieuse, vive",
        origin: "Latin",
      },
      {
        name: "Frankie",
        sign: "Libre et sincère",
        characteristics: "Honnête, joyeux",
        origin: "Anglais",
      },
      {
        name: "Fitz",
        sign: "Fils de",
        characteristics: "Noble, puissant",
        origin: "Anglais",
      },
      {
        name: "Frey",
        sign: "Seigneur des récoltes",
        characteristics: "Généreux, fort",
        origin: "Scandinave",
      },
      {
        name: "Faith",
        sign: "Confiance et foi",
        characteristics: "Fidèle, dévouée",
        origin: "Anglais",
      },
      {
        name: "Fergus",
        sign: "Homme de force",
        characteristics: "Fort, courageux",
        origin: "Gaélique",
      },
      {
        name: "Farah",
        sign: "Joyeuse et heureuse",
        characteristics: "Joyeuse, optimiste",
        origin: "Arabe",
      },
      {
        name: "Faye",
        sign: "Fée enchantée",
        characteristics: "Mystérieuse, douce",
        origin: "Anglais",
      },
      {
        name: "Forest",
        sign: "Homme de la forêt",
        characteristics: "Naturel, paisible",
        origin: "Français",
      },
      {
        name: "Finley",
        sign: "Guerrier blond",
        characteristics: "Courageux, fort",
        origin: "Gaélique",
      },
      {
        name: "Fiona",
        sign: "Blanche et juste",
        characteristics: "Pure, gracieuse",
        origin: "Gaélique",
      },
      {
        name: "Ferguson",
        sign: "Fils du choix",
        characteristics: "Noble, puissant",
        origin: "Écossais",
      },
      {
        name: "Flora",
        sign: "Déesse des fleurs",
        characteristics: "Gracieuse, douce",
        origin: "Latin",
      },
    ],
    background: "/cat6.png",
    description: `Les noms de chat commençant par 'F' évoquent souvent la fidélité et la force. Idéal pour les chats loyaux et robustes. "Felix", par exemple, signifie "heureux et chanceux" en latin, ce qui convient bien à un chat joyeux et optimiste.`,
  },
  g: {
    names: [
      {
        name: "Gus",
        sign: "Magnifique et grand",
        characteristics: "Fort, noble",
        origin: "Scandinave",
      },
      {
        name: "Grace",
        sign: "Symbole d'élégance",
        characteristics: "Gracieuse, douce",
        origin: "Latin",
      },
      {
        name: "Gavin",
        sign: "Faucon blanc",
        characteristics: "Courageux, loyal",
        origin: "Gallois",
      },
      {
        name: "Gemma",
        sign: "Pierre précieuse",
        characteristics: "Précieuse, brillante",
        origin: "Latin",
      },
      {
        name: "George",
        sign: "Travailleur de la terre",
        characteristics: "Travailleur, fort",
        origin: "Grec",
      },
      {
        name: "Giselle",
        sign: "Promesse",
        characteristics: "Fidèle, gracieuse",
        origin: "Allemand",
      },
      {
        name: "Gideon",
        sign: "Bûcheron puissant",
        characteristics: "Fort, courageux",
        origin: "Hébreu",
      },
      {
        name: "Gabby",
        sign: "Dérivé de Gabriel",
        characteristics: "Amicale, bavarde",
        origin: "Anglais",
      },
      {
        name: "Garrett",
        sign: "Dirigeant courageux",
        characteristics: "Brave, déterminé",
        origin: "Irlandais",
      },
      {
        name: "Gloria",
        sign: "Gloire céleste",
        characteristics: "Majestueuse, brillante",
        origin: "Latin",
      },
      {
        name: "Gina",
        sign: "Reine célèbre",
        characteristics: "Noble, gracieuse",
        origin: "Italien",
      },
      {
        name: "Graham",
        sign: "Maison grise",
        characteristics: "Stable, serein",
        origin: "Anglais",
      },
      {
        name: "Griffin",
        sign: "Créature légendaire",
        characteristics: "Fort, protecteur",
        origin: "Gallois",
      },
      {
        name: "Glenn",
        sign: "Vallée isolée",
        characteristics: "Paisible, naturel",
        origin: "Gaélique",
      },
      {
        name: "Giselle",
        sign: "Promesse",
        characteristics: "Fidèle, gracieuse",
        origin: "Allemand",
      },
      {
        name: "Gavin",
        sign: "Faucon blanc",
        characteristics: "Courageux, loyal",
        origin: "Gallois",
      },
      {
        name: "Gretel",
        sign: "Perle",
        characteristics: "Précieuse, rare",
        origin: "Allemand",
      },
      {
        name: "Gunner",
        sign: "Guerrier audacieux",
        characteristics: "Brave, audacieux",
        origin: "Scandinave",
      },
      {
        name: "Gemma",
        sign: "Pierre précieuse",
        characteristics: "Précieuse, brillante",
        origin: "Latin",
      },
      {
        name: "Gabriel",
        sign: "Homme de Dieu",
        characteristics: "Dévoué, protecteur",
        origin: "Hébreu",
      },
    ],
    background: "/cat7.png",
    description: `Les noms de chat commençant par 'G' sont souvent associés à la grandeur et à la grâce. Parfait pour les chats nobles et majestueux. "Gus", par exemple, signifie "magnifique et grand", ce qui convient bien à un chat fort et noble.`,
  },
  h: {
    names: [
      {
        name: "Henry",
        sign: "Roi puissant",
        characteristics: "Noble, fort",
        origin: "Allemand",
      },
      {
        name: "Hannah",
        sign: "Grâce divine",
        characteristics: "Gracieuse, douce",
        origin: "Hébreu",
      },
      {
        name: "Hugo",
        sign: "Esprit intelligent",
        characteristics: "Sage, brillant",
        origin: "Allemand",
      },
      {
        name: "Hazel",
        sign: "Noisette",
        characteristics: "Naturelle, douce",
        origin: "Anglais",
      },
      {
        name: "Harvey",
        sign: "Combattant de l'armée",
        characteristics: "Brave, déterminé",
        origin: "Français",
      },
      {
        name: "Helena",
        sign: "Lumière éclatante",
        characteristics: "Brillante, gracieuse",
        origin: "Grec",
      },
      {
        name: "Holden",
        sign: "Vallée creuse",
        characteristics: "Calme, paisible",
        origin: "Anglais",
      },
      {
        name: "Hector",
        sign: "Tenailler",
        characteristics: "Courageux, noble",
        origin: "Grec",
      },
      {
        name: "Hope",
        sign: "Espoir",
        characteristics: "Optimiste, joyeuse",
        origin: "Anglais",
      },
      {
        name: "Hudson",
        sign: "Fils de Hugh",
        characteristics: "Fort, déterminé",
        origin: "Anglais",
      },
      {
        name: "Holly",
        sign: "Arbre sacré",
        characteristics: "Naturelle, paisible",
        origin: "Anglais",
      },
      {
        name: "Haven",
        sign: "Lieu sûr",
        characteristics: "Protecteur, paisible",
        origin: "Anglais",
      },
      {
        name: "Harmony",
        sign: "Accord musical",
        characteristics: "Paisible, joyeuse",
        origin: "Anglais",
      },
      {
        name: "Hunter",
        sign: "Chasseur habile",
        characteristics: "Déterminé, audacieux",
        origin: "Anglais",
      },
      {
        name: "Harlow",
        sign: "Colline rocheuse",
        characteristics: "Fort, stable",
        origin: "Anglais",
      },
      {
        name: "Heidi",
        sign: "De noble naissance",
        characteristics: "Gracieuse, douce",
        origin: "Allemand",
      },
      {
        name: "Hugo",
        sign: "Esprit intelligent",
        characteristics: "Sage, brillant",
        origin: "Allemand",
      },
      {
        name: "Hector",
        sign: "Tenailler",
        characteristics: "Courageux, noble",
        origin: "Grec",
      },
      {
        name: "Harley",
        sign: "Prairie de lièvres",
        characteristics: "Naturel, libre",
        origin: "Anglais",
      },
      {
        name: "Harper",
        sign: "Joueur de harpe",
        characteristics: "Musical, créatif",
        origin: "Anglais",
      },
    ],
    background: "/cat8.png",
    description: `Les noms de chat commençant par 'H' évoquent souvent la harmonie et la noblesse. Idéal pour les chats paisibles et dignes. "Henry", par exemple, signifie "roi puissant", ce qui convient bien à un chat noble et fort.`,
  },
  i: {
    names: [
      {
        name: "Isla",
        sign: "Île",
        characteristics: "Paisible, unique",
        origin: "Écossais",
      },
      {
        name: "Isaac",
        sign: "Il rira",
        characteristics: "Joyeux, intelligent",
        origin: "Hébreu",
      },
      {
        name: "Ivy",
        sign: "Plante grimpante",
        characteristics: "Élégante, persistante",
        origin: "Anglais",
      },
      {
        name: "Ian",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, gentil",
        origin: "Écossais",
      },
      {
        name: "Iris",
        sign: "Arc-en-ciel",
        characteristics: "Colorée, joyeuse",
        origin: "Grec",
      },
      {
        name: "Indigo",
        sign: "Couleur profonde",
        characteristics: "Unique, mystérieux",
        origin: "Grec",
      },
      {
        name: "Imogen",
        sign: "Fille bien-aimée",
        characteristics: "Aimante, douce",
        origin: "Celtique",
      },
      {
        name: "Irwin",
        sign: "Ami de la mer",
        characteristics: "Loyal, fort",
        origin: "Anglais",
      },
      {
        name: "Irene",
        sign: "Paix",
        characteristics: "Paisible, douce",
        origin: "Grec",
      },
      {
        name: "Iago",
        sign: "Supplanteur",
        characteristics: "Fort, intelligent",
        origin: "Espagnol",
      },
      {
        name: "Isolde",
        sign: "Belle guerrière",
        characteristics: "Courageuse, forte",
        origin: "Germain",
      },
      {
        name: "Ingrid",
        sign: "Beauté légendaire",
        characteristics: "Gracieuse, noble",
        origin: "Scandinave",
      },
      {
        name: "Idris",
        sign: "Leader ardent",
        characteristics: "Fort, charismatique",
        origin: "Gallois",
      },
      {
        name: "India",
        sign: "Pays exotique",
        characteristics: "Unique, mystérieux",
        origin: "Latin",
      },
      {
        name: "Ishmael",
        sign: "Dieu écoutera",
        characteristics: "Pieux, fort",
        origin: "Hébreu",
      },
      {
        name: "Ilaria",
        sign: "Joyeuse et gaie",
        characteristics: "Optimiste, joyeuse",
        origin: "Latin",
      },
      {
        name: "Ivan",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, fort",
        origin: "Russe",
      },
      {
        name: "Isabella",
        sign: "Dieu est mon serment",
        characteristics: "Fidèle, gracieuse",
        origin: "Espagnol",
      },
      {
        name: "Ignatius",
        sign: "Plein de feu",
        characteristics: "Passionné, ardent",
        origin: "Latin",
      },
      {
        name: "Isadora",
        sign: "Cadeau d'Isis",
        characteristics: "Gracieuse, noble",
        origin: "Grec",
      },
    ],
    background: "/cat1.png",
    description: `Les noms de chat commençant par 'I' sont souvent associés à l'intelligence et à l'indépendance. Parfait pour les chats curieux et autonomes. "Isla", par exemple, signifie "île" en écossais, ce qui convient bien à une chatte paisible et unique.`,
  },
  j: {
    names: [
      {
        name: "Jack",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, gentil",
        origin: "Anglais",
      },
      {
        name: "Julia",
        sign: "Jeune et énergique",
        characteristics: "Énergique, joyeuse",
        origin: "Latin",
      },
      {
        name: "Jasper",
        sign: "Trésor précieux",
        characteristics: "Précieux, brillant",
        origin: "Persan",
      },
      {
        name: "Jade",
        sign: "Pierre précieuse",
        characteristics: "Précieuse, forte",
        origin: "Espagnol",
      },
      {
        name: "Julian",
        sign: "Jeune et énergique",
        characteristics: "Énergique, joyeux",
        origin: "Latin",
      },
      {
        name: "Jasmine",
        sign: "Fleur parfumée",
        characteristics: "Gracieuse, douce",
        origin: "Persan",
      },
      {
        name: "Jonas",
        sign: "Colombe",
        characteristics: "Paisible, doux",
        origin: "Hébreu",
      },
      {
        name: "Jenna",
        sign: "Petit oiseau",
        characteristics: "Libre, joyeuse",
        origin: "Anglais",
      },
      {
        name: "Jaxon",
        sign: "Fils de Jack",
        characteristics: "Loyal, fort",
        origin: "Anglais",
      },
      {
        name: "Joy",
        sign: "Joie et bonheur",
        characteristics: "Joyeuse, optimiste",
        origin: "Anglais",
      },
      {
        name: "Jett",
        sign: "Pierre noire",
        characteristics: "Mystérieux, fort",
        origin: "Anglais",
      },
      {
        name: "Josie",
        sign: "Dieu ajoutera",
        characteristics: "Dévouée, douce",
        origin: "Anglais",
      },
      {
        name: "Jared",
        sign: "Descendant",
        characteristics: "Noble, fort",
        origin: "Hébreu",
      },
      {
        name: "June",
        sign: "Le mois de juin",
        characteristics: "Été, joyeuse",
        origin: "Latin",
      },
      {
        name: "Jules",
        sign: "Jeune et énergique",
        characteristics: "Énergique, joyeux",
        origin: "Latin",
      },
      {
        name: "Jasmine",
        sign: "Fleur parfumée",
        characteristics: "Gracieuse, douce",
        origin: "Persan",
      },
      {
        name: "Jace",
        sign: "Guérisseur",
        characteristics: "Compatissant, fort",
        origin: "Grec",
      },
      {
        name: "Jamie",
        sign: "Celui qui supplante",
        characteristics: "Fort, déterminé",
        origin: "Écossais",
      },
      {
        name: "Jolie",
        sign: "Belle",
        characteristics: "Gracieuse, charmante",
        origin: "Français",
      },
      {
        name: "Joel",
        sign: "Dieu est Seigneur",
        characteristics: "Dévoué, fidèle",
        origin: "Hébreu",
      },
    ],
    background: "/cat10.png",
    description: `Les noms de chat commençant par 'J' évoquent souvent la joie et la jovialité. Idéal pour les chats joyeux et vifs. "Jack", par exemple, signifie "Dieu est gracieux", ce qui convient bien à un chat dévoué et gentil.`,
  },
  k: {
    names: [
      {
        name: "Kira",
        sign: "Rayon de lumière",
        characteristics: "Brillante, joyeuse",
        origin: "Russe",
      },
      {
        name: "Kai",
        sign: "Mer",
        characteristics: "Libre, aventureux",
        origin: "Hawaïen",
      },
      {
        name: "Keira",
        sign: "Petite et sombre",
        characteristics: "Mystérieuse, forte",
        origin: "Irlandais",
      },
      {
        name: "Kian",
        sign: "Ancien",
        characteristics: "Sage, noble",
        origin: "Irlandais",
      },
      {
        name: "Kylie",
        sign: "Boomerang",
        characteristics: "Énergique, joyeuse",
        origin: "Australien",
      },
      {
        name: "Knox",
        sign: "Colline",
        characteristics: "Stable, fort",
        origin: "Écossais",
      },
      {
        name: "Kara",
        sign: "Ami",
        characteristics: "Loyale, douce",
        origin: "Italien",
      },
      {
        name: "Kane",
        sign: "Guerrier",
        characteristics: "Courageux, fort",
        origin: "Irlandais",
      },
      {
        name: "Kiara",
        sign: "Claire et lumineuse",
        characteristics: "Brillante, joyeuse",
        origin: "Italien",
      },
      {
        name: "Kian",
        sign: "Ancien",
        characteristics: "Sage, noble",
        origin: "Irlandais",
      },
      {
        name: "Kody",
        sign: "Descendant",
        characteristics: "Loyal, fort",
        origin: "Anglais",
      },
      {
        name: "Kara",
        sign: "Ami",
        characteristics: "Loyale, douce",
        origin: "Italien",
      },
      {
        name: "Kieran",
        sign: "Petit et sombre",
        characteristics: "Mystérieux, fort",
        origin: "Irlandais",
      },
      {
        name: "Kendall",
        sign: "Vallée royale",
        characteristics: "Noble, élégant",
        origin: "Anglais",
      },
      {
        name: "Kasey",
        sign: "Vigilante",
        characteristics: "Attentive, courageuse",
        origin: "Irlandais",
      },
      {
        name: "Kade",
        sign: "Rond",
        characteristics: "Fort, stable",
        origin: "Anglais",
      },
      {
        name: "Keegan",
        sign: "Descendant ardent",
        characteristics: "Passionné, fort",
        origin: "Irlandais",
      },
      {
        name: "Kelsey",
        sign: "Île des navires",
        characteristics: "Aventureuse, libre",
        origin: "Anglais",
      },
    ],
    background: "/cat11.png",
    description: `Les noms de chat commençant par 'K' sont souvent associés à la noblesse et à la connaissance. Parfait pour les chats intelligents et gracieux. "Kira", par exemple, signifie "rayon de lumière", ce qui convient bien à une chatte brillante et joyeuse.`,
  },
  l: {
    names: [
      {
        name: "Liam",
        sign: "Guerrier déterminé",
        characteristics: "Courageux, fort",
        origin: "Irlandais",
      },
      {
        name: "Luna",
        sign: "Lune",
        characteristics: "Mystérieuse, calme",
        origin: "Latin",
      },
      {
        name: "Leo",
        sign: "Lion",
        characteristics: "Brave, fort",
        origin: "Latin",
      },
      {
        name: "Lila",
        sign: "Nuit",
        characteristics: "Mystérieuse, élégante",
        origin: "Arabe",
      },
      {
        name: "Logan",
        sign: "Petite crique",
        characteristics: "Aventureux, libre",
        origin: "Écossais",
      },
      {
        name: "Lucy",
        sign: "Lumière",
        characteristics: "Brillante, joyeuse",
        origin: "Latin",
      },
      {
        name: "Landon",
        sign: "Colline longue",
        characteristics: "Stable, fort",
        origin: "Anglais",
      },
      {
        name: "Layla",
        sign: "Nuit",
        characteristics: "Mystérieuse, élégante",
        origin: "Arabe",
      },
      {
        name: "Levi",
        sign: "Uni",
        characteristics: "Loyal, fort",
        origin: "Hébreu",
      },
      {
        name: "Lydia",
        sign: "De Lydia",
        characteristics: "Noble, élégante",
        origin: "Grec",
      },
      {
        name: "Lola",
        sign: "Douleur",
        characteristics: "Mystérieuse, forte",
        origin: "Espagnol",
      },
      {
        name: "Lucas",
        sign: "Lumière",
        characteristics: "Brillant, joyeux",
        origin: "Latin",
      },
      {
        name: "Lacey",
        sign: "De Lassy",
        characteristics: "Gracieuse, douce",
        origin: "Français",
      },
      {
        name: "Logan",
        sign: "Petite crique",
        characteristics: "Aventureux, libre",
        origin: "Écossais",
      },
      {
        name: "Lana",
        sign: "Roche douce",
        characteristics: "Gracieuse, douce",
        origin: "Gaélique",
      },
      {
        name: "Lincoln",
        sign: "Ville près du lac",
        characteristics: "Fort, déterminé",
        origin: "Anglais",
      },
      {
        name: "Lyle",
        sign: "Île",
        characteristics: "Serein, naturel",
        origin: "Français",
      },
      {
        name: "Livia",
        sign: "Olive",
        characteristics: "Paisible, gracieuse",
        origin: "Latin",
      },
      {
        name: "Louis",
        sign: "Guerrier célèbre",
        characteristics: "Courageux, noble",
        origin: "Français",
      },
      {
        name: "Lara",
        sign: "Citadelle",
        characteristics: "Forte, élégante",
        origin: "Grec",
      },
    ],
    background: "/cat12.png",
    description: `Les noms de chat commençant par 'L' évoquent souvent la lumière et l'amour. Idéal pour les chats affectueux et lumineux. "Luna", par exemple, signifie "lune", ce qui convient bien à une chatte mystérieuse et calme.`,
  },
  m: {
    names: [
      {
        name: "Milo",
        sign: "Gracieux et gentil",
        characteristics: "Douce, loyale",
        origin: "Allemand",
      },
      {
        name: "Mia",
        sign: "Mer",
        characteristics: "Libre, aventureuse",
        origin: "Scandinave",
      },
      {
        name: "Max",
        sign: "Le plus grand",
        characteristics: "Fort, déterminé",
        origin: "Latin",
      },
      {
        name: "Maya",
        sign: "Illusion",
        characteristics: "Mystérieuse, élégante",
        origin: "Sanskrit",
      },
      {
        name: "Miles",
        sign: "Soldat",
        characteristics: "Courageux, loyal",
        origin: "Anglais",
      },
      {
        name: "Mila",
        sign: "Aimée par le peuple",
        characteristics: "Aimante, joyeuse",
        origin: "Slave",
      },
      {
        name: "Mason",
        sign: "Travailleur des pierres",
        characteristics: "Travailleur, fort",
        origin: "Anglais",
      },
      {
        name: "Molly",
        sign: "Bitter",
        characteristics: "Forte, courageuse",
        origin: "Irlandais",
      },
      {
        name: "Maddox",
        sign: "Fils de Madoc",
        characteristics: "Noble, puissant",
        origin: "Gallois",
      },
      {
        name: "Mabel",
        sign: "Aimée",
        characteristics: "Douce, aimante",
        origin: "Latin",
      },
      {
        name: "Maeve",
        sign: "Elle qui enivre",
        characteristics: "Gracieuse, mystérieuse",
        origin: "Irlandais",
      },
      {
        name: "Morgan",
        sign: "Cercle de mer",
        characteristics: "Libre, naturel",
        origin: "Gallois",
      },
      {
        name: "Mira",
        sign: "Merveilleuse",
        characteristics: "Élégante, gracieuse",
        origin: "Latin",
      },
      {
        name: "Micah",
        sign: "Qui est comme Dieu",
        characteristics: "Dévoué, loyal",
        origin: "Hébreu",
      },
      {
        name: "Monica",
        sign: "Conseillère",
        characteristics: "Sage, fiable",
        origin: "Latin",
      },
      {
        name: "Mira",
        sign: "Merveilleuse",
        characteristics: "Élégante, gracieuse",
        origin: "Latin",
      },
      {
        name: "Megan",
        sign: "Perle",
        characteristics: "Précieuse, rare",
        origin: "Gallois",
      },
      {
        name: "Marshall",
        sign: "Guérisseur",
        characteristics: "Protecteur, fort",
        origin: "Anglais",
      },
      {
        name: "Maddie",
        sign: "Tour de force",
        characteristics: "Fort, déterminé",
        origin: "Anglais",
      },
    ],
    background: "/cat13.png",
    description: `Les noms de chat commençant par 'M' sont souvent associés à la majesté et à la douceur. Parfait pour les chats nobles et aimants. "Milo", par exemple, signifie "gracieux et gentil", ce qui convient bien à un chat doux et loyal.`,
  },
  n: {
    names: [
      {
        name: "Nora",
        sign: "Lumière",
        characteristics: "Brillante, douce",
        origin: "Irlandais",
      },
      {
        name: "Nolan",
        sign: "Champion",
        characteristics: "Fort, courageux",
        origin: "Irlandais",
      },
      {
        name: "Naomi",
        sign: "Plaisante",
        characteristics: "Gracieuse, douce",
        origin: "Hébreu",
      },
      {
        name: "Nina",
        sign: "Rêve",
        characteristics: "Élégante, mystérieuse",
        origin: "Espagnol",
      },
      {
        name: "Nathan",
        sign: "Don de Dieu",
        characteristics: "Généreux, loyal",
        origin: "Hébreu",
      },
      {
        name: "Nova",
        sign: "Nouvelle étoile",
        characteristics: "Brillante, unique",
        origin: "Latin",
      },
      {
        name: "Nash",
        sign: "Proche des frênes",
        characteristics: "Naturel, fort",
        origin: "Anglais",
      },
      {
        name: "Nia",
        sign: "But",
        characteristics: "Déterminée, forte",
        origin: "Gallois",
      },
      {
        name: "Neil",
        sign: "Champion",
        characteristics: "Brave, fort",
        origin: "Irlandais",
      },
      {
        name: "Nancy",
        sign: "Gracieuse",
        characteristics: "Douce, aimante",
        origin: "Hébreu",
      },
      {
        name: "Nico",
        sign: "Vainqueur du peuple",
        characteristics: "Fort, courageux",
        origin: "Grec",
      },
      {
        name: "Nell",
        sign: "Lumière",
        characteristics: "Brillante, douce",
        origin: "Anglais",
      },
      {
        name: "Nadia",
        sign: "Espoir",
        characteristics: "Optimiste, joyeuse",
        origin: "Russe",
      },
      {
        name: "Nash",
        sign: "Proche des frênes",
        characteristics: "Naturel, fort",
        origin: "Anglais",
      },
      {
        name: "Noel",
        sign: "Noël",
        characteristics: "Joyeux, aimant",
        origin: "Français",
      },
      {
        name: "Nova",
        sign: "Nouvelle étoile",
        characteristics: "Brillante, unique",
        origin: "Latin",
      },
      {
        name: "Nolan",
        sign: "Champion",
        characteristics: "Fort, courageux",
        origin: "Irlandais",
      },
      {
        name: "Niamh",
        sign: "Lumineuse",
        characteristics: "Brillante, gracieuse",
        origin: "Irlandais",
      },
      {
        name: "Nicolette",
        sign: "Petite victoire",
        characteristics: "Forte, courageuse",
        origin: "Français",
      },
      {
        name: "Newton",
        sign: "Nouvelle ville",
        characteristics: "Innovant, brillant",
        origin: "Anglais",
      },
    ],
    background: "/cat14.png",
    description: `Les noms de chat commençant par 'N' évoquent souvent la noblesse et la nouveauté. Idéal pour les chats élégants et uniques. "Nora", par exemple, signifie "lumière", ce qui convient bien à une chatte brillante et douce.`,
  },
  o: {
    names: [
      {
        name: "Olivia",
        sign: "Porteuse de paix",
        characteristics: "Paisible, gracieuse",
        origin: "Latin",
      },
      {
        name: "Oscar",
        sign: "Lance divine",
        characteristics: "Brave, fort",
        origin: "Germain",
      },
      {
        name: "Owen",
        sign: "Jeune guerrier",
        characteristics: "Courageux, loyal",
        origin: "Gallois",
      },
      {
        name: "Ophelia",
        sign: "Aide",
        characteristics: "Généreuse, douce",
        origin: "Grec",
      },
      {
        name: "Orion",
        sign: "Chasseur mythique",
        characteristics: "Fort, déterminé",
        origin: "Grec",
      },
      {
        name: "Odette",
        sign: "Riche",
        characteristics: "Noble, gracieuse",
        origin: "Français",
      },
      {
        name: "Omar",
        sign: "Flourissant",
        characteristics: "Énergique, joyeux",
        origin: "Arabe",
      },
      {
        name: "Otis",
        sign: "Riche",
        characteristics: "Noble, fort",
        origin: "Anglais",
      },
      {
        name: "Odessa",
        sign: "Voyageur",
        characteristics: "Aventureux, fort",
        origin: "Grec",
      },
      {
        name: "Orla",
        sign: "Princesse dorée",
        characteristics: "Noble, gracieuse",
        origin: "Irlandais",
      },
      {
        name: "Ozzy",
        sign: "Lance divine",
        characteristics: "Brave, fort",
        origin: "Anglais",
      },
      {
        name: "Oriana",
        sign: "Aurore",
        characteristics: "Éclatante, joyeuse",
        origin: "Latin",
      },
      {
        name: "Odin",
        sign: "Dieu suprême",
        characteristics: "Fort, sage",
        origin: "Scandinave",
      },
      {
        name: "Oakley",
        sign: "Prairie de chênes",
        characteristics: "Naturel, fort",
        origin: "Anglais",
      },
      {
        name: "Opal",
        sign: "Pierre précieuse",
        characteristics: "Précieuse, unique",
        origin: "Sanskrit",
      },
      {
        name: "Osmond",
        sign: "Protecteur divin",
        characteristics: "Protecteur, sage",
        origin: "Anglais",
      },
      {
        name: "Olga",
        sign: "Bénie",
        characteristics: "Gracieuse, noble",
        origin: "Scandinave",
      },
      {
        name: "Orion",
        sign: "Chasseur mythique",
        characteristics: "Fort, déterminé",
        origin: "Grec",
      },
      {
        name: "Odetta",
        sign: "Riche",
        characteristics: "Noble, gracieuse",
        origin: "Français",
      },
      {
        name: "Oswald",
        sign: "Puissant et divin",
        characteristics: "Fort, sage",
        origin: "Anglais",
      },
    ],
    background: "/cat15.png",
    description: `Les noms de chat commençant par 'O' sont souvent associés à l'originalité et à la force. Parfait pour les chats uniques et robustes. "Oscar", par exemple, signifie "lance divine", ce qui convient bien à un chat brave et fort.`,
  },
  p: {
    names: [
      {
        name: "Penny",
        sign: "Précieuse comme un centime",
        characteristics: "Économe, brillante",
        origin: "Anglais",
      },
      {
        name: "Patrick",
        sign: "Noble",
        characteristics: "Courageux, fidèle",
        origin: "Latin",
      },
      {
        name: "Pearl",
        sign: "Précieuse comme une perle",
        characteristics: "Pure, précieuse",
        origin: "Anglais",
      },
      {
        name: "Phoebe",
        sign: "Brillante et pure",
        characteristics: "Lumineuse, sage",
        origin: "Grec",
      },
      {
        name: "Parker",
        sign: "Gardien du parc",
        characteristics: "Protecteur, vigilant",
        origin: "Anglais",
      },
      {
        name: "Paisley",
        sign: "Motif floral",
        characteristics: "Créatif, unique",
        origin: "Écossais",
      },
      {
        name: "Pablo",
        sign: "Petit",
        characteristics: "Humble, gentil",
        origin: "Espagnol",
      },
      {
        name: "Paige",
        sign: "Jeune assistant",
        characteristics: "Aide, loyal",
        origin: "Anglais",
      },
      {
        name: "Peter",
        sign: "Pierre solide",
        characteristics: "Stable, fort",
        origin: "Grec",
      },
      {
        name: "Piper",
        sign: "Joueur de flûte",
        characteristics: "Musical, joyeux",
        origin: "Anglais",
      },
      {
        name: "Preston",
        sign: "Ville du prêtre",
        characteristics: "Sacré, noble",
        origin: "Anglais",
      },
      {
        name: "Poppy",
        sign: "Fleur de pavot",
        characteristics: "Colorée, vive",
        origin: "Anglais",
      },
      {
        name: "Porter",
        sign: "Gardien",
        characteristics: "Protecteur, vigilant",
        origin: "Anglais",
      },
      {
        name: "Paula",
        sign: "Petite",
        characteristics: "Humble, douce",
        origin: "Latin",
      },
      {
        name: "Philip",
        sign: "Ami des chevaux",
        characteristics: "Aventurier, loyal",
        origin: "Grec",
      },
      {
        name: "Primrose",
        sign: "Première rose",
        characteristics: "Gracieuse, élégante",
        origin: "Anglais",
      },
      {
        name: "Percy",
        sign: "Pierce valley",
        characteristics: "Noble, fort",
        origin: "Français",
      },
      {
        name: "Patricia",
        sign: "Noble",
        characteristics: "Gracieuse, douce",
        origin: "Latin",
      },
      {
        name: "Phoenix",
        sign: "Oiseau mythique",
        characteristics: "Résilient, fort",
        origin: "Grec",
      },
      {
        name: "Polly",
        sign: "Petit oiseau",
        characteristics: "Joyeuse, vive",
        origin: "Anglais",
      },
    ],
    background: "/cat16.png",
    description: `Les noms de chat commençant par 'P' évoquent souvent la paix et la protection. Idéal pour les chats paisibles et protecteurs. "Penny", par exemple, signifie "précieuse comme un centime", ce qui convient bien à une chatte économe et brillante.`,
  },
  q: {
    names: [
      {
        name: "Quinn",
        sign: "Chef sage",
        characteristics: "Sage, fort",
        origin: "Irlandais",
      },
      {
        name: "Quincy",
        sign: "Domaine des Cinq",
        characteristics: "Noble, unique",
        origin: "Français",
      },
      {
        name: "Quentin",
        sign: "Cinquième",
        characteristics: "Unique, déterminé",
        origin: "Latin",
      },
      {
        name: "Queenie",
        sign: "Petite reine",
        characteristics: "Noble, gracieuse",
        origin: "Anglais",
      },
      {
        name: "Quinlan",
        sign: "Forme gracieuse",
        characteristics: "Gracieux, élégant",
        origin: "Irlandais",
      },
      {
        name: "Quill",
        sign: "Plume",
        characteristics: "Créatif, léger",
        origin: "Anglais",
      },
      {
        name: "Quinton",
        sign: "Manoir des reines",
        characteristics: "Noble, fort",
        origin: "Anglais",
      },
      {
        name: "Quorra",
        sign: "Cœur",
        characteristics: "Aimante, douce",
        origin: "Italien",
      },
      {
        name: "Quest",
        sign: "Aventure",
        characteristics: "Aventurier, déterminé",
        origin: "Anglais",
      },
      {
        name: "Quilla",
        sign: "Déesse de la lune",
        characteristics: "Mystérieuse, douce",
        origin: "Inca",
      },
      {
        name: "Quartz",
        sign: "Cristal",
        characteristics: "Brillant, unique",
        origin: "Anglais",
      },
      {
        name: "Quorra",
        sign: "Cœur",
        characteristics: "Aimante, douce",
        origin: "Italien",
      },
      {
        name: "Quinby",
        sign: "Domaine de la reine",
        characteristics: "Noble, fort",
        origin: "Anglais",
      },
      {
        name: "Quirin",
        sign: "Portier",
        characteristics: "Vigilant, protecteur",
        origin: "Latin",
      },
      {
        name: "Questa",
        sign: "Chercheuse",
        characteristics: "Curieuse, aventurière",
        origin: "Espagnol",
      },
      {
        name: "Quella",
        sign: "Douce voix",
        characteristics: "Douce, aimante",
        origin: "Latin",
      },
      {
        name: "Quirinus",
        sign: "Portier",
        characteristics: "Vigilant, protecteur",
        origin: "Latin",
      },
      {
        name: "Quennell",
        sign: "Chêne",
        characteristics: "Fort, résilient",
        origin: "Anglais",
      },
      {
        name: "Questa",
        sign: "Chercheuse",
        characteristics: "Curieuse, aventurière",
        origin: "Espagnol",
      },
      {
        name: "Quillon",
        sign: "Croix",
        characteristics: "Dévoué, fort",
        origin: "Latin",
      },
    ],
    background: "/cat17.png",
    description: `Les noms de chat commençant par 'Q' sont souvent associés à la qualité et à la quiétude. Parfait pour les chats nobles et sereins. "Quinn", par exemple, signifie "chef sage", ce qui convient bien à un chat sage et fort.`,
  },
  r: {
    names: [
      {
        name: "Ruby",
        sign: "Pierre précieuse rouge",
        characteristics: "Précieuse, vibrante",
        origin: "Latin",
      },
      {
        name: "Ryan",
        sign: "Petit roi",
        characteristics: "Noble, fort",
        origin: "Irlandais",
      },
      {
        name: "Riley",
        sign: "Courageux",
        characteristics: "Brave, aventureux",
        origin: "Irlandais",
      },
      {
        name: "Rose",
        sign: "Fleur délicate",
        characteristics: "Gracieuse, douce",
        origin: "Latin",
      },
      {
        name: "Rex",
        sign: "Roi",
        characteristics: "Noble, puissant",
        origin: "Latin",
      },
      {
        name: "Rowan",
        sign: "Petit arbre rouge",
        characteristics: "Fort, résilient",
        origin: "Gaélique",
      },
      {
        name: "Reed",
        sign: "Roseau",
        characteristics: "Flexible, résilient",
        origin: "Anglais",
      },
      {
        name: "Rosie",
        sign: "Petite rose",
        characteristics: "Gracieuse, douce",
        origin: "Anglais",
      },
      {
        name: "Ronan",
        sign: "Petit phoque",
        characteristics: "Aventurier, libre",
        origin: "Irlandais",
      },
      {
        name: "Rhea",
        sign: "Flux",
        characteristics: "Élégante, douce",
        origin: "Grec",
      },
      {
        name: "Remy",
        sign: "Oarsman",
        characteristics: "Déterminé, fort",
        origin: "Français",
      },
      {
        name: "Rory",
        sign: "Roi rouge",
        characteristics: "Brave, noble",
        origin: "Irlandais",
      },
      {
        name: "Ruben",
        sign: "Vois, un fils",
        characteristics: "Joyeux, aimant",
        origin: "Hébreu",
      },
      {
        name: "Roxanne",
        sign: "Aube brillante",
        characteristics: "Lumineuse, gracieuse",
        origin: "Persan",
      },
      {
        name: "Robin",
        sign: "Petit oiseau",
        characteristics: "Joyeux, vif",
        origin: "Anglais",
      },
      {
        name: "Russell",
        sign: "Petit roux",
        characteristics: "Vibrant, énergique",
        origin: "Français",
      },
      {
        name: "Raven",
        sign: "Oiseau noir",
        characteristics: "Mystérieux, fort",
        origin: "Anglais",
      },
      {
        name: "Rosalind",
        sign: "Belle rose",
        characteristics: "Gracieuse, noble",
        origin: "Latin",
      },
      {
        name: "Rafael",
        sign: "Dieu a guéri",
        characteristics: "Dévoué, aimant",
        origin: "Hébreu",
      },
      {
        name: "Rita",
        sign: "Perle",
        characteristics: "Précieuse, rare",
        origin: "Espagnol",
      },
    ],
    background: "/cat18.png",
    description: `Les noms de chat commençant par 'R' évoquent souvent la royauté et la robustesse. Idéal pour les chats nobles et puissants. "Ruby", par exemple, signifie "pierre précieuse rouge", ce qui convient bien à une chatte précieuse et vibrante.`,
  },
  s: {
    names: [
      {
        name: "Sophia",
        sign: "Sagesse",
        characteristics: "Sage, gracieuse",
        origin: "Grec",
      },
      {
        name: "Samuel",
        sign: "Dieu a entendu",
        characteristics: "Dévoué, loyal",
        origin: "Hébreu",
      },
      {
        name: "Scarlett",
        sign: "Rouge éclatant",
        characteristics: "Passionnée, vive",
        origin: "Anglais",
      },
      {
        name: "Simon",
        sign: "Celui qui écoute",
        characteristics: "Attentif, intelligent",
        origin: "Hébreu",
      },
      {
        name: "Stella",
        sign: "Étoile",
        characteristics: "Brillante, joyeuse",
        origin: "Latin",
      },
      {
        name: "Sebastian",
        sign: "Vénérable",
        characteristics: "Noble, fort",
        origin: "Grec",
      },
      {
        name: "Sabrina",
        sign: "Fée légendaire",
        characteristics: "Mystérieuse, élégante",
        origin: "Celtique",
      },
      {
        name: "Soren",
        sign: "Sévère",
        characteristics: "Fort, résilient",
        origin: "Scandinave",
      },
      {
        name: "Sadie",
        sign: "Princesse",
        characteristics: "Noble, gracieuse",
        origin: "Hébreu",
      },
      {
        name: "Silas",
        sign: "Forêt",
        characteristics: "Naturel, serein",
        origin: "Latin",
      },
      {
        name: "Samantha",
        sign: "Auditeur",
        characteristics: "Attentive, douce",
        origin: "Araméen",
      },
      {
        name: "Sawyer",
        sign: "Coupeur de bois",
        characteristics: "Travailleur, fort",
        origin: "Anglais",
      },
      {
        name: "Serena",
        sign: "Calme",
        characteristics: "Paisible, douce",
        origin: "Latin",
      },
      {
        name: "Spencer",
        sign: "Distributeur",
        characteristics: "Généreux, loyal",
        origin: "Anglais",
      },
      {
        name: "Sullivan",
        sign: "Yeux noirs",
        characteristics: "Mystérieux, fort",
        origin: "Irlandais",
      },
      {
        name: "Sage",
        sign: "Sage",
        characteristics: "Intelligent, serein",
        origin: "Latin",
      },
      {
        name: "Sierra",
        sign: "Montagne",
        characteristics: "Forte, résiliente",
        origin: "Espagnol",
      },
      {
        name: "Sterling",
        sign: "Petit",
        characteristics: "Précieux, fort",
        origin: "Anglais",
      },
      {
        name: "Sadie",
        sign: "Princesse",
        characteristics: "Noble, gracieuse",
        origin: "Hébreu",
      },
      {
        name: "Skylar",
        sign: "Érudit",
        characteristics: "Intelligent, libre",
        origin: "Anglais",
      },
    ],
    background: "/cat2.png",
    description: `Les noms de chat commençant par 'S' sont souvent associés à la sagesse et à la sérénité. Parfait pour les chats intelligents et calmes. "Sophia", par exemple, signifie "sagesse", ce qui convient bien à une chatte sage et gracieuse.`,
  },
  t: {
    names: [
      {
        name: "Theodore",
        sign: "Cadeau de Dieu",
        characteristics: "Dévoué, noble",
        origin: "Grec",
      },
      {
        name: "Thomas",
        sign: "Jumeau",
        characteristics: "Loyal, intelligent",
        origin: "Araméen",
      },
      {
        name: "Talia",
        sign: "Rosée de Dieu",
        characteristics: "Pure, douce",
        origin: "Hébreu",
      },
      {
        name: "Tristan",
        sign: "Tumulte",
        characteristics: "Aventureux, courageux",
        origin: "Celtique",
      },
      {
        name: "Tara",
        sign: "Colline",
        characteristics: "Stable, paisible",
        origin: "Irlandais",
      },
      {
        name: "Tyler",
        sign: "Fabricant de tuiles",
        characteristics: "Travailleur, créatif",
        origin: "Anglais",
      },
      {
        name: "Tess",
        sign: "Récolte",
        characteristics: "Gracieuse, aimante",
        origin: "Grec",
      },
      {
        name: "Tobias",
        sign: "Dieu est bon",
        characteristics: "Dévoué, aimant",
        origin: "Hébreu",
      },
      {
        name: "Travis",
        sign: "Traversée",
        characteristics: "Aventurier, déterminé",
        origin: "Français",
      },
      {
        name: "Tamara",
        sign: "Palmier",
        characteristics: "Gracieuse, forte",
        origin: "Hébreu",
      },
      {
        name: "Troy",
        sign: "Soldat",
        characteristics: "Brave, fort",
        origin: "Anglais",
      },
      {
        name: "Thalia",
        sign: "Fleurissante",
        characteristics: "Joyeuse, gracieuse",
        origin: "Grec",
      },
      {
        name: "Trevor",
        sign: "Grand village",
        characteristics: "Stable, fort",
        origin: "Gallois",
      },
      {
        name: "Tatiana",
        sign: "Fée reine",
        characteristics: "Gracieuse, noble",
        origin: "Latin",
      },
      {
        name: "Tobin",
        sign: "Dieu est bon",
        characteristics: "Dévoué, aimant",
        origin: "Hébreu",
      },
      {
        name: "Tiffany",
        sign: "Manifestation de Dieu",
        characteristics: "Gracieuse, noble",
        origin: "Grec",
      },
      {
        name: "Trent",
        sign: "Aventurier",
        characteristics: "Courageux, fort",
        origin: "Anglais",
      },
      {
        name: "Tatum",
        sign: "Apporteur de joie",
        characteristics: "Joyeux, vif",
        origin: "Anglais",
      },
      {
        name: "Teagan",
        sign: "Poète",
        characteristics: "Créatif, doux",
        origin: "Irlandais",
      },
      {
        name: "Tyson",
        sign: "Feu ardent",
        characteristics: "Passionné, énergique",
        origin: "Anglais",
      },
    ],
    background: "/cat4.png",
    description: `Les noms de chat commençant par 'T' évoquent souvent la ténacité et la tranquillité. Idéal pour les chats déterminés et paisibles. "Theodore", par exemple, signifie "cadeau de Dieu", ce qui convient bien à un chat dévoué et noble.`,
  },
  u: {
    names: [
      {
        name: "Uma",
        sign: "Lumière",
        characteristics: "Brillante, douce",
        origin: "Sanskrit",
      },
      {
        name: "Ulysses",
        sign: "Colère",
        characteristics: "Déterminé, fort",
        origin: "Grec",
      },
      {
        name: "Uriel",
        sign: "Dieu est ma lumière",
        characteristics: "Dévoué, lumineux",
        origin: "Hébreu",
      },
      {
        name: "Ursula",
        sign: "Petite ourse",
        characteristics: "Forte, protectrice",
        origin: "Latin",
      },
      {
        name: "Ulrich",
        sign: "Héritier puissant",
        characteristics: "Noble, fort",
        origin: "Allemand",
      },
      {
        name: "Unity",
        sign: "Unité",
        characteristics: "Harmonieuse, paisible",
        origin: "Anglais",
      },
      {
        name: "Uma",
        sign: "Lumière",
        characteristics: "Brillante, douce",
        origin: "Sanskrit",
      },
      {
        name: "Uriah",
        sign: "Dieu est ma lumière",
        characteristics: "Dévoué, lumineux",
        origin: "Hébreu",
      },
      {
        name: "Ulani",
        sign: "Joyeux",
        characteristics: "Joyeux, optimiste",
        origin: "Hawaïen",
      },
      {
        name: "Upton",
        sign: "Ville haute",
        characteristics: "Noble, fort",
        origin: "Anglais",
      },
      {
        name: "Umar",
        sign: "Flourissant",
        characteristics: "Énergique, joyeux",
        origin: "Arabe",
      },
      {
        name: "Ulma",
        sign: "Célèbre",
        characteristics: "Réputée, noble",
        origin: "Allemand",
      },
      {
        name: "Urban",
        sign: "De la ville",
        characteristics: "Sociable, vif",
        origin: "Latin",
      },
      {
        name: "Ursa",
        sign: "Ours",
        characteristics: "Forte, protectrice",
        origin: "Latin",
      },
      {
        name: "Usher",
        sign: "Gardien",
        characteristics: "Vigilant, fort",
        origin: "Anglais",
      },
      {
        name: "Umberto",
        sign: "Guerrier brillant",
        characteristics: "Brave, lumineux",
        origin: "Italien",
      },
      {
        name: "Ulric",
        sign: "Héritier puissant",
        characteristics: "Noble, fort",
        origin: "Allemand",
      },
      {
        name: "Ulla",
        sign: "Volonté déterminée",
        characteristics: "Déterminée, forte",
        origin: "Scandinave",
      },
      {
        name: "Ugo",
        sign: "Esprit brillant",
        characteristics: "Sage, vif",
        origin: "Italien",
      },
      {
        name: "Uri",
        sign: "Lumière de Dieu",
        characteristics: "Dévoué, lumineux",
        origin: "Hébreu",
      },
    ],
    background: "/cat1.png",
    description: `Les noms de chat commençant par 'U' sont souvent associés à l'unicité et à l'unité. Parfait pour les chats uniques et harmonieux. "Uma", par exemple, signifie "lumière", ce qui convient bien à une chatte brillante et douce.`,
  },
  v: {
    names: [
      {
        name: "Violet",
        sign: "Fleur violette",
        characteristics: "Gracieuse, douce",
        origin: "Latin",
      },
      {
        name: "Victor",
        sign: "Vainqueur",
        characteristics: "Fort, déterminé",
        origin: "Latin",
      },
      {
        name: "Valeria",
        sign: "Valeureuse",
        characteristics: "Courageuse, noble",
        origin: "Latin",
      },
      {
        name: "Vincent",
        sign: "Conquérant",
        characteristics: "Déterminé, fort",
        origin: "Latin",
      },
      {
        name: "Valentina",
        sign: "Forte et saine",
        characteristics: "Courageuse, noble",
        origin: "Latin",
      },
      {
        name: "Vera",
        sign: "Vérité",
        characteristics: "Honnête, douce",
        origin: "Russe",
      },
      {
        name: "Vaughn",
        sign: "Petit",
        characteristics: "Humble, vif",
        origin: "Gallois",
      },
      {
        name: "Vivian",
        sign: "Vivante",
        characteristics: "Énergique, joyeuse",
        origin: "Latin",
      },
      {
        name: "Valerie",
        sign: "Forte et saine",
        characteristics: "Courageuse, noble",
        origin: "Latin",
      },
      {
        name: "Vance",
        sign: "Habitant des marais",
        characteristics: "Naturel, libre",
        origin: "Anglais",
      },
      {
        name: "Vienna",
        sign: "Ville en Autriche",
        characteristics: "Culturelle, élégante",
        origin: "Latin",
      },
      {
        name: "Vanessa",
        sign: "Papillon",
        characteristics: "Gracieuse, légère",
        origin: "Grec",
      },
      {
        name: "Vito",
        sign: "Vie",
        characteristics: "Énergique, joyeux",
        origin: "Italien",
      },
      {
        name: "Valen",
        sign: "Fort et vigoureux",
        characteristics: "Fort, déterminé",
        origin: "Latin",
      },
      {
        name: "Vivienne",
        sign: "Vivante",
        characteristics: "Énergique, joyeuse",
        origin: "Latin",
      },
      {
        name: "Victoire",
        sign: "Victoire",
        characteristics: "Gagnante, déterminée",
        origin: "Français",
      },
      {
        name: "Vali",
        sign: "Choisi",
        characteristics: "Unique, fort",
        origin: "Nordique",
      },
      {
        name: "Vesper",
        sign: "Étoile du soir",
        characteristics: "Mystérieuse, calme",
        origin: "Latin",
      },
      {
        name: "Vail",
        sign: "Vallée",
        characteristics: "Paisible, naturelle",
        origin: "Anglais",
      },
      {
        name: "Vita",
        sign: "Vie",
        characteristics: "Énergique, joyeuse",
        origin: "Latin",
      },
    ],
    background: "/cat5.png",
    description: `Les noms de chat commençant par 'V' évoquent souvent la vitalité et la vaillance. Idéal pour les chats énergiques et courageux. "Violet", par exemple, signifie "fleur violette", ce qui convient bien à une chatte gracieuse et douce.`,
  },
  w: {
    names: [
      {
        name: "Willow",
        sign: "Arbre gracieux",
        characteristics: "Flexible, douce",
        origin: "Anglais",
      },
      {
        name: "William",
        sign: "Protecteur déterminé",
        characteristics: "Courageux, fort",
        origin: "Allemand",
      },
      {
        name: "Wren",
        sign: "Petit oiseau",
        characteristics: "Vif, joyeux",
        origin: "Anglais",
      },
      {
        name: "Wade",
        sign: "Traversée",
        characteristics: "Aventurier, déterminé",
        origin: "Anglais",
      },
      {
        name: "Winona",
        sign: "Fille aînée",
        characteristics: "Aimante, douce",
        origin: "Amérindien",
      },
      {
        name: "Wyatt",
        sign: "Brave au combat",
        characteristics: "Courageux, fort",
        origin: "Anglais",
      },
      {
        name: "Willa",
        sign: "Déterminée et protectrice",
        characteristics: "Protectrice, douce",
        origin: "Allemand",
      },
      {
        name: "Winston",
        sign: "Ville joyeuse",
        characteristics: "Joyeux, vif",
        origin: "Anglais",
      },
      {
        name: "Wesley",
        sign: "Prairie de l'ouest",
        characteristics: "Naturel, paisible",
        origin: "Anglais",
      },
      {
        name: "Whitney",
        sign: "Île blanche",
        characteristics: "Pure, paisible",
        origin: "Anglais",
      },
      {
        name: "Waldo",
        sign: "Dirigeant puissant",
        characteristics: "Noble, fort",
        origin: "Allemand",
      },
      {
        name: "Wilfred",
        sign: "Paix voulue",
        characteristics: "Paisible, déterminé",
        origin: "Anglais",
      },
      {
        name: "Waverly",
        sign: "Prairie de trembles",
        characteristics: "Naturelle, douce",
        origin: "Anglais",
      },
      {
        name: "Wallace",
        sign: "Étranger",
        characteristics: "Unique, noble",
        origin: "Anglais",
      },
      {
        name: "Wynn",
        sign: "Ami béni",
        characteristics: "Loyal, doux",
        origin: "Gallois",
      },
      {
        name: "Ward",
        sign: "Gardien",
        characteristics: "Protecteur, vigilant",
        origin: "Anglais",
      },
      {
        name: "Whit",
        sign: "Blanc",
        characteristics: "Pur, vif",
        origin: "Anglais",
      },
      {
        name: "Wrenley",
        sign: "Bois de petits oiseaux",
        characteristics: "Vif, naturel",
        origin: "Anglais",
      },
      {
        name: "Wolf",
        sign: "Loup",
        characteristics: "Fort, loyal",
        origin: "Anglais",
      },
      {
        name: "Willa",
        sign: "Déterminée et protectrice",
        characteristics: "Protectrice, douce",
        origin: "Allemand",
      },
    ],
    background: "/cat6.png",
    description: `Les noms de chat commençant par 'W' sont souvent associés à la volonté et à la vigueur. Parfait pour les chats déterminés et forts. "Willow", par exemple, signifie "arbre gracieux", ce qui convient bien à une chatte flexible et douce.`,
  },
  x: {
    names: [
      {
        name: "Xander",
        sign: "Défenseur des hommes",
        characteristics: "Protecteur, fort",
        origin: "Grec",
      },
      {
        name: "Xavier",
        sign: "Maison neuve",
        characteristics: "Innovant, vif",
        origin: "Basque",
      },
      {
        name: "Xena",
        sign: "Étrangère",
        characteristics: "Unique, forte",
        origin: "Grec",
      },
      {
        name: "Ximena",
        sign: "Écoute",
        characteristics: "Attentive, douce",
        origin: "Espagnol",
      },
      {
        name: "Xyla",
        sign: "De la forêt",
        characteristics: "Naturelle, paisible",
        origin: "Grec",
      },
      {
        name: "Xerxes",
        sign: "Souverain",
        characteristics: "Noble, puissant",
        origin: "Persan",
      },
      {
        name: "Xanthe",
        sign: "Jaune",
        characteristics: "Brillante, joyeuse",
        origin: "Grec",
      },
      {
        name: "Xenia",
        sign: "Hospitalité",
        characteristics: "Accueillante, douce",
        origin: "Grec",
      },
      {
        name: "Xylon",
        sign: "De la forêt",
        characteristics: "Naturel, fort",
        origin: "Grec",
      },
      {
        name: "Xavi",
        sign: "Maison neuve",
        characteristics: "Innovant, vif",
        origin: "Basque",
      },
      {
        name: "Xara",
        sign: "Princesse",
        characteristics: "Noble, gracieuse",
        origin: "Arabe",
      },
      {
        name: "Xiomara",
        sign: "Fameuse au combat",
        characteristics: "Courageuse, forte",
        origin: "Espagnol",
      },
      {
        name: "Xyla",
        sign: "De la forêt",
        characteristics: "Naturelle, paisible",
        origin: "Grec",
      },
      {
        name: "Xena",
        sign: "Étrangère",
        characteristics: "Unique, forte",
        origin: "Grec",
      },
      {
        name: "Xanthe",
        sign: "Jaune",
        characteristics: "Brillante, joyeuse",
        origin: "Grec",
      },
      {
        name: "Ximen",
        sign: "Écoute",
        characteristics: "Attentif, loyal",
        origin: "Espagnol",
      },
      {
        name: "Xavi",
        sign: "Maison neuve",
        characteristics: "Innovant, vif",
        origin: "Basque",
      },
      {
        name: "Xiomara",
        sign: "Fameuse au combat",
        characteristics: "Courageuse, forte",
        origin: "Espagnol",
      },
    ],
    background: "/cat7.png",
    description: `Les noms de chat commençant par 'X' évoquent souvent l'exotisme et l'excellence. Idéal pour les chats uniques et nobles. "Xander", par exemple, signifie "défenseur des hommes", ce qui convient bien à un chat protecteur et fort.`,
  },
  y: {
    names: [
      {
        name: "Yara",
        sign: "Petite papillon",
        characteristics: "Légère, gracieuse",
        origin: "Arabe",
      },
      {
        name: "Yves",
        sign: "If",
        characteristics: "Fort, noble",
        origin: "Français",
      },
      {
        name: "Yasmin",
        sign: "Fleur de jasmin",
        characteristics: "Douce, élégante",
        origin: "Persan",
      },
      {
        name: "Yanni",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, joyeux",
        origin: "Grec",
      },
      {
        name: "Yulia",
        sign: "Jeune",
        characteristics: "Énergique, joyeuse",
        origin: "Slavon",
      },
      {
        name: "Yosef",
        sign: "Dieu ajoutera",
        characteristics: "Fidèle, fort",
        origin: "Hébreu",
      },
      {
        name: "Yvette",
        sign: "If",
        characteristics: "Fort, noble",
        origin: "Français",
      },
      {
        name: "Yuri",
        sign: "Lys",
        characteristics: "Pur, noble",
        origin: "Russe",
      },
      {
        name: "Yasmina",
        sign: "Fleur de jasmin",
        characteristics: "Douce, élégante",
        origin: "Persan",
      },
      {
        name: "Yohan",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, loyal",
        origin: "Hébreu",
      },
      {
        name: "Yasmin",
        sign: "Fleur de jasmin",
        characteristics: "Douce, élégante",
        origin: "Persan",
      },
      {
        name: "Yosef",
        sign: "Dieu ajoutera",
        characteristics: "Fidèle, fort",
        origin: "Hébreu",
      },
      {
        name: "Yuki",
        sign: "Neige",
        characteristics: "Pure, douce",
        origin: "Japonais",
      },
      {
        name: "Yelena",
        sign: "Lumière brillante",
        characteristics: "Lumineuse, joyeuse",
        origin: "Russe",
      },
      {
        name: "Yasmine",
        sign: "Fleur de jasmin",
        characteristics: "Douce, élégante",
        origin: "Persan",
      },
      {
        name: "Yannis",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, joyeux",
        origin: "Grec",
      },
      {
        name: "Yuki",
        sign: "Neige",
        characteristics: "Pure, douce",
        origin: "Japonais",
      },
    ],
    background: "/cat8.png",
    description: `Les noms de chat commençant par 'Y' sont souvent associés à la jeunesse et à la joie. Parfait pour les chats joyeux et vifs. "Yara", par exemple, signifie "petit papillon", ce qui convient bien à une chatte légère et gracieuse.`,
  },
  z: {
    names: [
      {
        name: "Zoe",
        sign: "Vie",
        characteristics: "Énergique, joyeuse",
        origin: "Grec",
      },
      {
        name: "Zane",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, fort",
        origin: "Hébreu",
      },
      {
        name: "Zara",
        sign: "Princesse",
        characteristics: "Noble, gracieuse",
        origin: "Arabe",
      },
      {
        name: "Zachary",
        sign: "Souvenir de Dieu",
        characteristics: "Dévoué, fidèle",
        origin: "Hébreu",
      },
      {
        name: "Zelda",
        sign: "Guerrière grise",
        characteristics: "Courageuse, forte",
        origin: "Germain",
      },
      {
        name: "Zion",
        sign: "Terre promise",
        characteristics: "Sacré, noble",
        origin: "Hébreu",
      },
      {
        name: "Zara",
        sign: "Princesse",
        characteristics: "Noble, gracieuse",
        origin: "Arabe",
      },
      {
        name: "Zane",
        sign: "Dieu est gracieux",
        characteristics: "Dévoué, fort",
        origin: "Hébreu",
      },
      {
        name: "Zora",
        sign: "Aurore",
        characteristics: "Lumineuse, joyeuse",
        origin: "Slavon",
      },
      {
        name: "Zeke",
        sign: "Dieu renforce",
        characteristics: "Fort, résilient",
        origin: "Hébreu",
      },
      {
        name: "Zinnia",
        sign: "Fleur",
        characteristics: "Colorée, vive",
        origin: "Latin",
      },
      {
        name: "Zephyr",
        sign: "Vent de l'ouest",
        characteristics: "Libre, vif",
        origin: "Grec",
      },
      {
        name: "Zahara",
        sign: "Fleur",
        characteristics: "Élégante, douce",
        origin: "Arabe",
      },
      {
        name: "Zayden",
        sign: "Abondant",
        characteristics: "Énergique, joyeux",
        origin: "Arabe",
      },
      {
        name: "Ziva",
        sign: "Lumineuse",
        characteristics: "Lumineuse, joyeuse",
        origin: "Hébreu",
      },
      {
        name: "Zaylee",
        sign: "Fée",
        characteristics: "Gracieuse, joyeuse",
        origin: "Anglais",
      },
      {
        name: "Zander",
        sign: "Défenseur des hommes",
        characteristics: "Protecteur, fort",
        origin: "Grec",
      },
      {
        name: "Zuri",
        sign: "Belle",
        characteristics: "Gracieuse, joyeuse",
        origin: "Swahili",
      },
      {
        name: "Zeb",
        sign: "Don de Dieu",
        characteristics: "Généreux, fort",
        origin: "Hébreu",
      },
      {
        name: "Zola",
        sign: "Calme",
        characteristics: "Paisible, douce",
        origin: "Sud-africain",
      },
    ],
    background: "/cat10.png",
    description: `Les noms de chat commençant par 'Z' évoquent souvent la zénitude et le zèle. Idéal pour les chats calmes et énergiques. "Zoe", par exemple, signifie "vie", ce qui convient bien à une chatte énergique et joyeuse.`,
  },
};
